### ISSUE TITLE
snaphu unwrapping problem

### ISSUE THREAD

**Issue by hzq2311** [insarlab/MiaplPy#16]
Hi, I use snaphu to unwrapping interferograms under maiplpy framwork. the size of interferogram is 7259 * 27044 generated by part of full frame sentinel-1A SAR IW data. But the snaphu tile mode doesn't work, it shows Exceeded maximum number of secondary nodes Decrease TILECOSTTHRESH and/or increase MINREGIONSIZE. I try to adjust TILECOSTTHRESH  and MINREGIONSIZE, and unwrapping still auto exit in some places. I have to increase the snaphu.tileNumPixels to force a single piece process, it works. but the one piece process consumes a lot of time and memory, I cann't image how to process full frame data. 
Does anyone to Unwrapping full frame interferogram by snaphu? cause I saw the Chen and Zebker's paper it shows a 23240 * 4800 pixel interferogram unwrapping result in 2002.  It shouldn't be a problem by now. how can i solve this problem？

another problem is I set the mask file path in config file, but the snaphu still unwrapping the full region even some area  outside the mask, why?

![image](https://user-images.githubusercontent.com/17444734/177245107-7264a677-b49b-45f4-ac5a-a523dbbad379.png)
![image](https://user-images.githubusercontent.com/17444734/177245209-d2649b42-1c33-430f-89e6-be38e12d02e6.png)

**Comment by otirmizi** [comment]
Hi @hzq2311 ,

I ran into the same error in the unwrapping step (b'Exceeded maximum number of secondary arcs\nDecrease TILECOSTTHRESH and/or increase MINREGIONSIZE\n').  Apparently snaphu sometimes has issues when working in full resolution but there is a quick workaround that should not affect your workflow.

In the main miaplpy folder, there should be a file called conf.full. You can add a new parameter (MINREGIONSIZE or TILECOSTTHRESH) and define a value for it based on the information here: https://web.stanford.edu/group/radar/softwareandlinks/sw/snaphu/snaphu.conf.full 

For example, I added MINREGIONSIZE with a value of 200 (default is 100) and it resolved the issue for me.

Make sure you hit enter and leave a blank line at the end of conf.full otherwise you might get something similar to the following error when the conf_all file in each individual folder is generated: b'illegal argument 200DEFOMAX_CYCLE for parameter MINREGIONSIZE (/../../miaplpy/inverted/interferograms_single_reference/20181026_20201214/config_all:12)\n'

Hope this helps!

**Comment by mirzaees** [comment]
@otirmizi Thanks for replying. @hzq2311 The unwrapping of the full frame is not a problem if it is coherent and up to now they were usually multilooked. But for full resolution when it is decorrelated in most of the regions, those parameters may not work. You need to play with them to be able to unwrap. Generally I do not recommend unwrapping a full frame in full resolution with snaphu

For masking, snaphu accepts a certain formatting and the unwrap mask is generated in step 3 based on what you set in config file, if you set it after step 3 it will not work. The solution is to use this script (generate_unwrap_mask.py) and give it your custom mask with .h5 format, the output will be saved to 'inverted/mask_unwrap' which will be used in unwrapping

**Comment by mirzaees** [comment]
I suppose this issue is resolved, I am closing it

**Comment by HollyleafSTK** [comment]
How to determine how much I should decrease TILECOSTTHRESH or increase MINREGIONSIZE? I do set it either same message or bunch errors.

**Comment by mirzaees** [comment]
This is a good question but for snaphu, I don't know exactly what it should be, I think it depends on your data.

**Comment by HollyleafSTK** [comment]
It's depend on data size?

**Comment by HollyleafSTK** [comment]
It's depend on data size?
My image is a set of ALOS2 WD1 (bandwidth 14MHz, descending) with 6367 x 21784 size, I'd try if this worked or not?
![image](https://github.com/user-attachments/assets/91e452cb-cad3-473b-94e9-f1b871fe6f53)
